/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    name: string;
}
export interface Card {
    id: bigint;
    xp?: bigint;
    nftEligible?: boolean;
    edition?: string;
    owner: Principal;
    cardType: string;
    name: string;
    tags?: Array<string>;
    lastForgedAt?: bigint;
    level?: bigint;
    marketLocked?: boolean;
    cardClass?: string;
    rarity?: string;
    power: bigint;
    forgeTier?: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Tournament {
    id: bigint;
    participants: Array<Principal>;
    rankings: Array<Principal>;
    name: string;
    isActive: boolean;
}
export interface BattleResult {
    id: bigint;
    winner: Principal;
    player1: Principal;
    player2: Principal;
    timestamp: bigint;
}
export interface MarketTransaction {
    id: bigint;
    itemId: bigint;
    isCompleted: boolean;
    seller: Principal;
    itemType: string;
    buyer?: Principal;
    price: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface PlayerAccount {
    owner: Principal;
    name: string;
    level: bigint;
    experience: bigint;
}
export interface Stronghold {
    assignedDefenceDeckId?: bigint;
    owner: Principal;
    upgrades: Array<string>;
    level: bigint;
    assignedRaidDeckId?: bigint;
}
export interface Deck {
    id: bigint;
    owner: Principal;
    name: string;
    cardIds: Array<bigint>;
    power: bigint;
}
export interface SoftWallet {
    owner: Principal;
    food: bigint;
    gold: bigint;
    iron: bigint;
    mana: bigint;
    stone: bigint;
    mythex: bigint;
    lumber: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface CraftingRecipe {
    id: bigint;
    name: string;
    materials: Array<string>;
    resultItem: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blob_hash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignDefenceDeck(deckId: bigint): Promise<void>;
    assignRaidDeck(deckId: bigint): Promise<void>;
    awardXpToCard(cardId: bigint, xpAmount: bigint): Promise<void>;
    cancelMarketListing(transactionId: bigint): Promise<void>;
    collectStarterResources(): Promise<void>;
    completePurchase(transactionId: bigint): Promise<void>;
    craftItem(recipeId: bigint): Promise<string>;
    createCard(name: string, power: bigint, cardType: string): Promise<bigint>;
    createCraftingRecipe(name: string, materials: Array<string>, resultItem: string): Promise<bigint>;
    createDeck(name: string, cardIds: Array<bigint>): Promise<bigint>;
    createMarketListing(itemType: string, itemId: bigint, price: bigint): Promise<bigint>;
    createPlayerAccount(name: string): Promise<bigint>;
    createStronghold(): Promise<void>;
    createTournament(name: string): Promise<bigint>;
    earnMythex(amount: bigint): Promise<void>;
    earnResources(gold: bigint, stone: bigint, lumber: bigint, iron: bigint, food: bigint, mana: bigint): Promise<void>;
    forgeCards(targetCardId: bigint, sacrificeCardIds: Array<bigint>): Promise<void>;
    getAllBattleResults(): Promise<Array<BattleResult>>;
    getAllCraftingRecipes(): Promise<Array<CraftingRecipe>>;
    getAllMarketListings(): Promise<Array<MarketTransaction>>;
    getAllTournaments(): Promise<Array<Tournament>>;
    getBattleResult(id: bigint): Promise<BattleResult | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCard(id: bigint): Promise<Card | null>;
    getCraftingRecipe(id: bigint): Promise<CraftingRecipe | null>;
    getDeck(id: bigint): Promise<Deck | null>;
    getMarketListing(id: bigint): Promise<MarketTransaction | null>;
    getMyCards(): Promise<Array<Card>>;
    getMyDecks(): Promise<Array<Deck>>;
    getMyMarketListings(): Promise<Array<MarketTransaction>>;
    getMyPlayerAccount(): Promise<PlayerAccount | null>;
    getMySoftWallet(): Promise<SoftWallet | null>;
    getMyStronghold(): Promise<Stronghold | null>;
    getMythexBalance(): Promise<bigint>;
    getPlayerAccount(id: bigint): Promise<PlayerAccount | null>;
    getPlayerCards(owner: Principal): Promise<Array<Card>>;
    getPlayerDecks(owner: Principal): Promise<Array<Deck>>;
    getSoftWallet(owner: Principal): Promise<SoftWallet | null>;
    getStronghold(owner: Principal): Promise<Stronghold | null>;
    getTournament(id: bigint): Promise<Tournament | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    grantBattleRewards(player: Principal, isWin: boolean): Promise<void>;
    grantCardToPlayer(player: Principal, name: string, power: bigint, cardType: string): Promise<bigint>;
    grantTournamentRewards(player: Principal, placement: bigint): Promise<void>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    joinTournament(tournamentId: bigint): Promise<void>;
    recordBattle(player1: Principal, player2: Principal, winner: Principal): Promise<bigint>;
    removeCard(cardId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    spendMythex(amount: bigint): Promise<void>;
    spendResources(gold: bigint, stone: bigint, lumber: bigint, iron: bigint, food: bigint, mana: bigint): Promise<void>;
    updateCard(cardId: bigint, level: bigint | null, xp: bigint | null, forgeTier: bigint | null, nftEligible: boolean | null, lastForgedAt: bigint | null, marketLocked: boolean | null): Promise<void>;
    updateDeck(deckId: bigint, name: string, cardIds: Array<bigint>): Promise<void>;
    updatePlayerAccount(level: bigint, experience: bigint): Promise<void>;
    updateTournamentRankings(tournamentId: bigint, rankings: Array<Principal>): Promise<void>;
    upgradeStronghold(newLevel: bigint, newUpgrades: Array<string>): Promise<void>;
}
import type { BattleResult as _BattleResult, Card as _Card, CraftingRecipe as _CraftingRecipe, Deck as _Deck, MarketTransaction as _MarketTransaction, PlayerAccount as _PlayerAccount, SoftWallet as _SoftWallet, Stronghold as _Stronghold, Tournament as _Tournament, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async assignDefenceDeck(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignDefenceDeck(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignDefenceDeck(arg0);
            return result;
        }
    }
    async assignRaidDeck(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignRaidDeck(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignRaidDeck(arg0);
            return result;
        }
    }
    async awardXpToCard(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.awardXpToCard(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.awardXpToCard(arg0, arg1);
            return result;
        }
    }
    async cancelMarketListing(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelMarketListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelMarketListing(arg0);
            return result;
        }
    }
    async collectStarterResources(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.collectStarterResources();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.collectStarterResources();
            return result;
        }
    }
    async completePurchase(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completePurchase(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completePurchase(arg0);
            return result;
        }
    }
    async craftItem(arg0: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.craftItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.craftItem(arg0);
            return result;
        }
    }
    async createCard(arg0: string, arg1: bigint, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCard(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCard(arg0, arg1, arg2);
            return result;
        }
    }
    async createCraftingRecipe(arg0: string, arg1: Array<string>, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCraftingRecipe(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCraftingRecipe(arg0, arg1, arg2);
            return result;
        }
    }
    async createDeck(arg0: string, arg1: Array<bigint>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createDeck(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDeck(arg0, arg1);
            return result;
        }
    }
    async createMarketListing(arg0: string, arg1: bigint, arg2: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createMarketListing(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMarketListing(arg0, arg1, arg2);
            return result;
        }
    }
    async createPlayerAccount(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPlayerAccount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPlayerAccount(arg0);
            return result;
        }
    }
    async createStronghold(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createStronghold();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStronghold();
            return result;
        }
    }
    async createTournament(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTournament(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTournament(arg0);
            return result;
        }
    }
    async earnMythex(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.earnMythex(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.earnMythex(arg0);
            return result;
        }
    }
    async earnResources(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.earnResources(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.earnResources(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async forgeCards(arg0: bigint, arg1: Array<bigint>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.forgeCards(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.forgeCards(arg0, arg1);
            return result;
        }
    }
    async getAllBattleResults(): Promise<Array<BattleResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBattleResults();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBattleResults();
            return result;
        }
    }
    async getAllCraftingRecipes(): Promise<Array<CraftingRecipe>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCraftingRecipes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCraftingRecipes();
            return result;
        }
    }
    async getAllMarketListings(): Promise<Array<MarketTransaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMarketListings();
                return from_candid_vec_n10(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMarketListings();
            return from_candid_vec_n10(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllTournaments(): Promise<Array<Tournament>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTournaments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTournaments();
            return result;
        }
    }
    async getBattleResult(arg0: bigint): Promise<BattleResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBattleResult(arg0);
                return from_candid_opt_n14(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBattleResult(arg0);
            return from_candid_opt_n14(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n15(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n15(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n16(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n16(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCard(arg0: bigint): Promise<Card | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCard(arg0);
                return from_candid_opt_n18(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCard(arg0);
            return from_candid_opt_n18(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCraftingRecipe(arg0: bigint): Promise<CraftingRecipe | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCraftingRecipe(arg0);
                return from_candid_opt_n23(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCraftingRecipe(arg0);
            return from_candid_opt_n23(this.uploadFile, this.downloadFile, result);
        }
    }
    async getDeck(arg0: bigint): Promise<Deck | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeck(arg0);
                return from_candid_opt_n24(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeck(arg0);
            return from_candid_opt_n24(this.uploadFile, this.downloadFile, result);
        }
    }
    async getMarketListing(arg0: bigint): Promise<MarketTransaction | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketListing(arg0);
                return from_candid_opt_n25(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketListing(arg0);
            return from_candid_opt_n25(this.uploadFile, this.downloadFile, result);
        }
    }
    async getMyCards(): Promise<Array<Card>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyCards();
                return from_candid_vec_n26(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyCards();
            return from_candid_vec_n26(this.uploadFile, this.downloadFile, result);
        }
    }
    async getMyDecks(): Promise<Array<Deck>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyDecks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyDecks();
            return result;
        }
    }
    async getMyMarketListings(): Promise<Array<MarketTransaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyMarketListings();
                return from_candid_vec_n10(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyMarketListings();
            return from_candid_vec_n10(this.uploadFile, this.downloadFile, result);
        }
    }
    async getMyPlayerAccount(): Promise<PlayerAccount | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPlayerAccount();
                return from_candid_opt_n27(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPlayerAccount();
            return from_candid_opt_n27(this.uploadFile, this.downloadFile, result);
        }
    }
    async getMySoftWallet(): Promise<SoftWallet | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySoftWallet();
                return from_candid_opt_n28(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySoftWallet();
            return from_candid_opt_n28(this.uploadFile, this.downloadFile, result);
        }
    }
    async getMyStronghold(): Promise<Stronghold | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyStronghold();
                return from_candid_opt_n29(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyStronghold();
            return from_candid_opt_n29(this.uploadFile, this.downloadFile, result);
        }
    }
    async getMythexBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getMythexBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMythexBalance();
            return result;
        }
    }
    async getPlayerAccount(arg0: bigint): Promise<PlayerAccount | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerAccount(arg0);
                return from_candid_opt_n27(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerAccount(arg0);
            return from_candid_opt_n27(this.uploadFile, this.downloadFile, result);
        }
    }
    async getPlayerCards(arg0: Principal): Promise<Array<Card>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerCards(arg0);
                return from_candid_vec_n26(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerCards(arg0);
            return from_candid_vec_n26(this.uploadFile, this.downloadFile, result);
        }
    }
    async getPlayerDecks(arg0: Principal): Promise<Array<Deck>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerDecks(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerDecks(arg0);
            return result;
        }
    }
    async getSoftWallet(arg0: Principal): Promise<SoftWallet | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSoftWallet(arg0);
                return from_candid_opt_n28(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSoftWallet(arg0);
            return from_candid_opt_n28(this.uploadFile, this.downloadFile, result);
        }
    }
    async getStronghold(arg0: Principal): Promise<Stronghold | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStronghold(arg0);
                return from_candid_opt_n29(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStronghold(arg0);
            return from_candid_opt_n29(this.uploadFile, this.downloadFile, result);
        }
    }
    async getTournament(arg0: bigint): Promise<Tournament | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTournament(arg0);
                return from_candid_opt_n32(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTournament(arg0);
            return from_candid_opt_n32(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n15(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n15(this.uploadFile, this.downloadFile, result);
        }
    }
    async grantBattleRewards(arg0: Principal, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.grantBattleRewards(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.grantBattleRewards(arg0, arg1);
            return result;
        }
    }
    async grantCardToPlayer(arg0: Principal, arg1: string, arg2: bigint, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.grantCardToPlayer(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.grantCardToPlayer(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async grantTournamentRewards(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.grantTournamentRewards(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.grantTournamentRewards(arg0, arg1);
            return result;
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async joinTournament(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.joinTournament(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinTournament(arg0);
            return result;
        }
    }
    async recordBattle(arg0: Principal, arg1: Principal, arg2: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.recordBattle(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordBattle(arg0, arg1, arg2);
            return result;
        }
    }
    async removeCard(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeCard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeCard(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async spendMythex(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.spendMythex(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.spendMythex(arg0);
            return result;
        }
    }
    async spendResources(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.spendResources(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.spendResources(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateCard(arg0: bigint, arg1: bigint | null, arg2: bigint | null, arg3: bigint | null, arg4: boolean | null, arg5: bigint | null, arg6: boolean | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCard(arg0, to_candid_opt_n33(this.uploadFile, this.downloadFile, arg1), to_candid_opt_n33(this.uploadFile, this.downloadFile, arg2), to_candid_opt_n33(this.uploadFile, this.downloadFile, arg3), to_candid_opt_n34(this.uploadFile, this.downloadFile, arg4), to_candid_opt_n33(this.uploadFile, this.downloadFile, arg5), to_candid_opt_n34(this.uploadFile, this.downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCard(arg0, to_candid_opt_n33(this.uploadFile, this.downloadFile, arg1), to_candid_opt_n33(this.uploadFile, this.downloadFile, arg2), to_candid_opt_n33(this.uploadFile, this.downloadFile, arg3), to_candid_opt_n34(this.uploadFile, this.downloadFile, arg4), to_candid_opt_n33(this.uploadFile, this.downloadFile, arg5), to_candid_opt_n34(this.uploadFile, this.downloadFile, arg6));
            return result;
        }
    }
    async updateDeck(arg0: bigint, arg1: string, arg2: Array<bigint>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDeck(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDeck(arg0, arg1, arg2);
            return result;
        }
    }
    async updatePlayerAccount(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlayerAccount(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlayerAccount(arg0, arg1);
            return result;
        }
    }
    async updateTournamentRankings(arg0: bigint, arg1: Array<Principal>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTournamentRankings(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTournamentRankings(arg0, arg1);
            return result;
        }
    }
    async upgradeStronghold(arg0: bigint, arg1: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.upgradeStronghold(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upgradeStronghold(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Card_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Card): Card {
    return from_candid_record_n20(uploadFile, downloadFile, value);
}
function from_candid_MarketTransaction_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MarketTransaction): MarketTransaction {
    return from_candid_record_n12(uploadFile, downloadFile, value);
}
function from_candid_Stronghold_n30(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Stronghold): Stronghold {
    return from_candid_record_n31(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n17(uploadFile, downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(uploadFile, downloadFile, value);
}
function from_candid_opt_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BattleResult]): BattleResult | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Card]): Card | null {
    return value.length === 0 ? null : from_candid_Card_n19(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n21(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<string>]): Array<string> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CraftingRecipe]): CraftingRecipe | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Deck]): Deck | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MarketTransaction]): MarketTransaction | null {
    return value.length === 0 ? null : from_candid_MarketTransaction_n11(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n27(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlayerAccount]): PlayerAccount | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SoftWallet]): SoftWallet | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Stronghold]): Stronghold | null {
    return value.length === 0 ? null : from_candid_Stronghold_n30(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n32(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Tournament]): Tournament | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    itemId: bigint;
    isCompleted: boolean;
    seller: Principal;
    itemType: string;
    buyer: [] | [Principal];
    price: bigint;
}): {
    id: bigint;
    itemId: bigint;
    isCompleted: boolean;
    seller: Principal;
    itemType: string;
    buyer?: Principal;
    price: bigint;
} {
    return {
        id: value.id,
        itemId: value.itemId,
        isCompleted: value.isCompleted,
        seller: value.seller,
        itemType: value.itemType,
        buyer: record_opt_to_undefined(from_candid_opt_n13(uploadFile, downloadFile, value.buyer)),
        price: value.price
    };
}
function from_candid_record_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    xp: [] | [bigint];
    nftEligible: [] | [boolean];
    edition: [] | [string];
    owner: Principal;
    cardType: string;
    name: string;
    tags: [] | [Array<string>];
    lastForgedAt: [] | [bigint];
    level: [] | [bigint];
    marketLocked: [] | [boolean];
    cardClass: [] | [string];
    rarity: [] | [string];
    power: bigint;
    forgeTier: [] | [bigint];
}): {
    id: bigint;
    xp?: bigint;
    nftEligible?: boolean;
    edition?: string;
    owner: Principal;
    cardType: string;
    name: string;
    tags?: Array<string>;
    lastForgedAt?: bigint;
    level?: bigint;
    marketLocked?: boolean;
    cardClass?: string;
    rarity?: string;
    power: bigint;
    forgeTier?: bigint;
} {
    return {
        id: value.id,
        xp: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.xp)),
        nftEligible: record_opt_to_undefined(from_candid_opt_n6(uploadFile, downloadFile, value.nftEligible)),
        edition: record_opt_to_undefined(from_candid_opt_n21(uploadFile, downloadFile, value.edition)),
        owner: value.owner,
        cardType: value.cardType,
        name: value.name,
        tags: record_opt_to_undefined(from_candid_opt_n22(uploadFile, downloadFile, value.tags)),
        lastForgedAt: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.lastForgedAt)),
        level: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.level)),
        marketLocked: record_opt_to_undefined(from_candid_opt_n6(uploadFile, downloadFile, value.marketLocked)),
        cardClass: record_opt_to_undefined(from_candid_opt_n21(uploadFile, downloadFile, value.cardClass)),
        rarity: record_opt_to_undefined(from_candid_opt_n21(uploadFile, downloadFile, value.rarity)),
        power: value.power,
        forgeTier: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.forgeTier))
    };
}
function from_candid_record_n31(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    assignedDefenceDeckId: [] | [bigint];
    owner: Principal;
    upgrades: Array<string>;
    level: bigint;
    assignedRaidDeckId: [] | [bigint];
}): {
    assignedDefenceDeckId?: bigint;
    owner: Principal;
    upgrades: Array<string>;
    level: bigint;
    assignedRaidDeckId?: bigint;
} {
    return {
        assignedDefenceDeckId: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.assignedDefenceDeckId)),
        owner: value.owner,
        upgrades: value.upgrades,
        level: value.level,
        assignedRaidDeckId: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.assignedRaidDeckId))
    };
}
function from_candid_record_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(uploadFile, downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MarketTransaction>): Array<MarketTransaction> {
    return value.map((x)=>from_candid_MarketTransaction_n11(uploadFile, downloadFile, x));
}
function from_candid_vec_n26(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Card>): Array<Card> {
    return value.map((x)=>from_candid_Card_n19(uploadFile, downloadFile, x));
}
function to_candid_UserRole_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(uploadFile, downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(uploadFile, downloadFile, value);
}
function to_candid_opt_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(uploadFile, downloadFile, value));
}
function to_candid_opt_n33(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n34(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: boolean | null): [] | [boolean] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
