/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BattleResult = IDL.Record({
  'id' : IDL.Nat,
  'winner' : IDL.Principal,
  'player1' : IDL.Principal,
  'player2' : IDL.Principal,
  'timestamp' : IDL.Nat,
});
export const CraftingRecipe = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'materials' : IDL.Vec(IDL.Text),
  'resultItem' : IDL.Text,
});
export const MarketTransaction = IDL.Record({
  'id' : IDL.Nat,
  'itemId' : IDL.Nat,
  'isCompleted' : IDL.Bool,
  'seller' : IDL.Principal,
  'itemType' : IDL.Text,
  'buyer' : IDL.Opt(IDL.Principal),
  'price' : IDL.Nat,
});
export const Tournament = IDL.Record({
  'id' : IDL.Nat,
  'participants' : IDL.Vec(IDL.Principal),
  'rankings' : IDL.Vec(IDL.Principal),
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Card = IDL.Record({
  'id' : IDL.Nat,
  'xp' : IDL.Opt(IDL.Nat),
  'nftEligible' : IDL.Opt(IDL.Bool),
  'edition' : IDL.Opt(IDL.Text),
  'owner' : IDL.Principal,
  'cardType' : IDL.Text,
  'name' : IDL.Text,
  'tags' : IDL.Opt(IDL.Vec(IDL.Text)),
  'lastForgedAt' : IDL.Opt(IDL.Nat),
  'level' : IDL.Opt(IDL.Nat),
  'marketLocked' : IDL.Opt(IDL.Bool),
  'cardClass' : IDL.Opt(IDL.Text),
  'rarity' : IDL.Opt(IDL.Text),
  'power' : IDL.Nat,
  'forgeTier' : IDL.Opt(IDL.Nat),
});
export const Deck = IDL.Record({
  'id' : IDL.Nat,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'cardIds' : IDL.Vec(IDL.Nat),
  'power' : IDL.Nat,
});
export const PlayerAccount = IDL.Record({
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'level' : IDL.Nat,
  'experience' : IDL.Nat,
});
export const SoftWallet = IDL.Record({
  'owner' : IDL.Principal,
  'food' : IDL.Nat,
  'gold' : IDL.Nat,
  'iron' : IDL.Nat,
  'mana' : IDL.Nat,
  'stone' : IDL.Nat,
  'mythex' : IDL.Nat,
  'lumber' : IDL.Nat,
});
export const Stronghold = IDL.Record({
  'assignedDefenceDeckId' : IDL.Opt(IDL.Nat),
  'owner' : IDL.Principal,
  'upgrades' : IDL.Vec(IDL.Text),
  'level' : IDL.Nat,
  'assignedRaidDeckId' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignDefenceDeck' : IDL.Func([IDL.Nat], [], []),
  'assignRaidDeck' : IDL.Func([IDL.Nat], [], []),
  'awardXpToCard' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'cancelMarketListing' : IDL.Func([IDL.Nat], [], []),
  'collectStarterResources' : IDL.Func([], [], []),
  'completePurchase' : IDL.Func([IDL.Nat], [], []),
  'craftItem' : IDL.Func([IDL.Nat], [IDL.Text], []),
  'createCard' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
  'createCraftingRecipe' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createDeck' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat)], [IDL.Nat], []),
  'createMarketListing' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [IDL.Nat], []),
  'createPlayerAccount' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'createStronghold' : IDL.Func([], [], []),
  'createTournament' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'earnMythex' : IDL.Func([IDL.Nat], [], []),
  'earnResources' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'forgeCards' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Nat)], [], []),
  'getAllBattleResults' : IDL.Func([], [IDL.Vec(BattleResult)], ['query']),
  'getAllCraftingRecipes' : IDL.Func([], [IDL.Vec(CraftingRecipe)], ['query']),
  'getAllMarketListings' : IDL.Func(
      [],
      [IDL.Vec(MarketTransaction)],
      ['query'],
    ),
  'getAllTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
  'getBattleResult' : IDL.Func([IDL.Nat], [IDL.Opt(BattleResult)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCard' : IDL.Func([IDL.Nat], [IDL.Opt(Card)], ['query']),
  'getCraftingRecipe' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(CraftingRecipe)],
      ['query'],
    ),
  'getDeck' : IDL.Func([IDL.Nat], [IDL.Opt(Deck)], ['query']),
  'getMarketListing' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(MarketTransaction)],
      ['query'],
    ),
  'getMyCards' : IDL.Func([], [IDL.Vec(Card)], ['query']),
  'getMyDecks' : IDL.Func([], [IDL.Vec(Deck)], ['query']),
  'getMyMarketListings' : IDL.Func([], [IDL.Vec(MarketTransaction)], ['query']),
  'getMyPlayerAccount' : IDL.Func([], [IDL.Opt(PlayerAccount)], ['query']),
  'getMySoftWallet' : IDL.Func([], [IDL.Opt(SoftWallet)], ['query']),
  'getMyStronghold' : IDL.Func([], [IDL.Opt(Stronghold)], ['query']),
  'getMythexBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getPlayerAccount' : IDL.Func([IDL.Nat], [IDL.Opt(PlayerAccount)], ['query']),
  'getPlayerCards' : IDL.Func([IDL.Principal], [IDL.Vec(Card)], ['query']),
  'getPlayerDecks' : IDL.Func([IDL.Principal], [IDL.Vec(Deck)], ['query']),
  'getSoftWallet' : IDL.Func([IDL.Principal], [IDL.Opt(SoftWallet)], ['query']),
  'getStronghold' : IDL.Func([IDL.Principal], [IDL.Opt(Stronghold)], ['query']),
  'getTournament' : IDL.Func([IDL.Nat], [IDL.Opt(Tournament)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'grantBattleRewards' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
  'grantCardToPlayer' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'grantTournamentRewards' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinTournament' : IDL.Func([IDL.Nat], [], []),
  'recordBattle' : IDL.Func(
      [IDL.Principal, IDL.Principal, IDL.Principal],
      [IDL.Nat],
      [],
    ),
  'removeCard' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'spendMythex' : IDL.Func([IDL.Nat], [], []),
  'spendResources' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'updateCard' : IDL.Func(
      [
        IDL.Nat,
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Bool),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Bool),
      ],
      [],
      [],
    ),
  'updateDeck' : IDL.Func([IDL.Nat, IDL.Text, IDL.Vec(IDL.Nat)], [], []),
  'updatePlayerAccount' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateTournamentRankings' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Principal)],
      [],
      [],
    ),
  'upgradeStronghold' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Text)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BattleResult = IDL.Record({
    'id' : IDL.Nat,
    'winner' : IDL.Principal,
    'player1' : IDL.Principal,
    'player2' : IDL.Principal,
    'timestamp' : IDL.Nat,
  });
  const CraftingRecipe = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'materials' : IDL.Vec(IDL.Text),
    'resultItem' : IDL.Text,
  });
  const MarketTransaction = IDL.Record({
    'id' : IDL.Nat,
    'itemId' : IDL.Nat,
    'isCompleted' : IDL.Bool,
    'seller' : IDL.Principal,
    'itemType' : IDL.Text,
    'buyer' : IDL.Opt(IDL.Principal),
    'price' : IDL.Nat,
  });
  const Tournament = IDL.Record({
    'id' : IDL.Nat,
    'participants' : IDL.Vec(IDL.Principal),
    'rankings' : IDL.Vec(IDL.Principal),
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Card = IDL.Record({
    'id' : IDL.Nat,
    'xp' : IDL.Opt(IDL.Nat),
    'nftEligible' : IDL.Opt(IDL.Bool),
    'edition' : IDL.Opt(IDL.Text),
    'owner' : IDL.Principal,
    'cardType' : IDL.Text,
    'name' : IDL.Text,
    'tags' : IDL.Opt(IDL.Vec(IDL.Text)),
    'lastForgedAt' : IDL.Opt(IDL.Nat),
    'level' : IDL.Opt(IDL.Nat),
    'marketLocked' : IDL.Opt(IDL.Bool),
    'cardClass' : IDL.Opt(IDL.Text),
    'rarity' : IDL.Opt(IDL.Text),
    'power' : IDL.Nat,
    'forgeTier' : IDL.Opt(IDL.Nat),
  });
  const Deck = IDL.Record({
    'id' : IDL.Nat,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'cardIds' : IDL.Vec(IDL.Nat),
    'power' : IDL.Nat,
  });
  const PlayerAccount = IDL.Record({
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'level' : IDL.Nat,
    'experience' : IDL.Nat,
  });
  const SoftWallet = IDL.Record({
    'owner' : IDL.Principal,
    'food' : IDL.Nat,
    'gold' : IDL.Nat,
    'iron' : IDL.Nat,
    'mana' : IDL.Nat,
    'stone' : IDL.Nat,
    'mythex' : IDL.Nat,
    'lumber' : IDL.Nat,
  });
  const Stronghold = IDL.Record({
    'assignedDefenceDeckId' : IDL.Opt(IDL.Nat),
    'owner' : IDL.Principal,
    'upgrades' : IDL.Vec(IDL.Text),
    'level' : IDL.Nat,
    'assignedRaidDeckId' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignDefenceDeck' : IDL.Func([IDL.Nat], [], []),
    'assignRaidDeck' : IDL.Func([IDL.Nat], [], []),
    'awardXpToCard' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'cancelMarketListing' : IDL.Func([IDL.Nat], [], []),
    'collectStarterResources' : IDL.Func([], [], []),
    'completePurchase' : IDL.Func([IDL.Nat], [], []),
    'craftItem' : IDL.Func([IDL.Nat], [IDL.Text], []),
    'createCard' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
    'createCraftingRecipe' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createDeck' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat)], [IDL.Nat], []),
    'createMarketListing' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'createPlayerAccount' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'createStronghold' : IDL.Func([], [], []),
    'createTournament' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'earnMythex' : IDL.Func([IDL.Nat], [], []),
    'earnResources' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'forgeCards' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Nat)], [], []),
    'getAllBattleResults' : IDL.Func([], [IDL.Vec(BattleResult)], ['query']),
    'getAllCraftingRecipes' : IDL.Func(
        [],
        [IDL.Vec(CraftingRecipe)],
        ['query'],
      ),
    'getAllMarketListings' : IDL.Func(
        [],
        [IDL.Vec(MarketTransaction)],
        ['query'],
      ),
    'getAllTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
    'getBattleResult' : IDL.Func([IDL.Nat], [IDL.Opt(BattleResult)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCard' : IDL.Func([IDL.Nat], [IDL.Opt(Card)], ['query']),
    'getCraftingRecipe' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(CraftingRecipe)],
        ['query'],
      ),
    'getDeck' : IDL.Func([IDL.Nat], [IDL.Opt(Deck)], ['query']),
    'getMarketListing' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(MarketTransaction)],
        ['query'],
      ),
    'getMyCards' : IDL.Func([], [IDL.Vec(Card)], ['query']),
    'getMyDecks' : IDL.Func([], [IDL.Vec(Deck)], ['query']),
    'getMyMarketListings' : IDL.Func(
        [],
        [IDL.Vec(MarketTransaction)],
        ['query'],
      ),
    'getMyPlayerAccount' : IDL.Func([], [IDL.Opt(PlayerAccount)], ['query']),
    'getMySoftWallet' : IDL.Func([], [IDL.Opt(SoftWallet)], ['query']),
    'getMyStronghold' : IDL.Func([], [IDL.Opt(Stronghold)], ['query']),
    'getMythexBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getPlayerAccount' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(PlayerAccount)],
        ['query'],
      ),
    'getPlayerCards' : IDL.Func([IDL.Principal], [IDL.Vec(Card)], ['query']),
    'getPlayerDecks' : IDL.Func([IDL.Principal], [IDL.Vec(Deck)], ['query']),
    'getSoftWallet' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(SoftWallet)],
        ['query'],
      ),
    'getStronghold' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(Stronghold)],
        ['query'],
      ),
    'getTournament' : IDL.Func([IDL.Nat], [IDL.Opt(Tournament)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'grantBattleRewards' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
    'grantCardToPlayer' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'grantTournamentRewards' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinTournament' : IDL.Func([IDL.Nat], [], []),
    'recordBattle' : IDL.Func(
        [IDL.Principal, IDL.Principal, IDL.Principal],
        [IDL.Nat],
        [],
      ),
    'removeCard' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'spendMythex' : IDL.Func([IDL.Nat], [], []),
    'spendResources' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'updateCard' : IDL.Func(
        [
          IDL.Nat,
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Bool),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Bool),
        ],
        [],
        [],
      ),
    'updateDeck' : IDL.Func([IDL.Nat, IDL.Text, IDL.Vec(IDL.Nat)], [], []),
    'updatePlayerAccount' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateTournamentRankings' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Principal)],
        [],
        [],
      ),
    'upgradeStronghold' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Text)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };