/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BattleResult {
  'id' : bigint,
  'winner' : Principal,
  'player1' : Principal,
  'player2' : Principal,
  'timestamp' : bigint,
}
export interface Card {
  'id' : bigint,
  'xp' : [] | [bigint],
  'nftEligible' : [] | [boolean],
  'edition' : [] | [string],
  'owner' : Principal,
  'cardType' : string,
  'name' : string,
  'tags' : [] | [Array<string>],
  'lastForgedAt' : [] | [bigint],
  'level' : [] | [bigint],
  'marketLocked' : [] | [boolean],
  'cardClass' : [] | [string],
  'rarity' : [] | [string],
  'power' : bigint,
  'forgeTier' : [] | [bigint],
}
export interface CraftingRecipe {
  'id' : bigint,
  'name' : string,
  'materials' : Array<string>,
  'resultItem' : string,
}
export interface Deck {
  'id' : bigint,
  'owner' : Principal,
  'name' : string,
  'cardIds' : Array<bigint>,
  'power' : bigint,
}
export interface MarketTransaction {
  'id' : bigint,
  'itemId' : bigint,
  'isCompleted' : boolean,
  'seller' : Principal,
  'itemType' : string,
  'buyer' : [] | [Principal],
  'price' : bigint,
}
export interface PlayerAccount {
  'owner' : Principal,
  'name' : string,
  'level' : bigint,
  'experience' : bigint,
}
export interface SoftWallet {
  'owner' : Principal,
  'food' : bigint,
  'gold' : bigint,
  'iron' : bigint,
  'mana' : bigint,
  'stone' : bigint,
  'mythex' : bigint,
  'lumber' : bigint,
}
export interface Stronghold {
  'assignedDefenceDeckId' : [] | [bigint],
  'owner' : Principal,
  'upgrades' : Array<string>,
  'level' : bigint,
  'assignedRaidDeckId' : [] | [bigint],
}
export interface Tournament {
  'id' : bigint,
  'participants' : Array<Principal>,
  'rankings' : Array<Principal>,
  'name' : string,
  'isActive' : boolean,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignDefenceDeck' : ActorMethod<[bigint], undefined>,
  'assignRaidDeck' : ActorMethod<[bigint], undefined>,
  'awardXpToCard' : ActorMethod<[bigint, bigint], undefined>,
  'cancelMarketListing' : ActorMethod<[bigint], undefined>,
  'collectStarterResources' : ActorMethod<[], undefined>,
  'completePurchase' : ActorMethod<[bigint], undefined>,
  'craftItem' : ActorMethod<[bigint], string>,
  'createCard' : ActorMethod<[string, bigint, string], bigint>,
  'createCraftingRecipe' : ActorMethod<[string, Array<string>, string], bigint>,
  'createDeck' : ActorMethod<[string, Array<bigint>], bigint>,
  'createMarketListing' : ActorMethod<[string, bigint, bigint], bigint>,
  'createPlayerAccount' : ActorMethod<[string], bigint>,
  'createStronghold' : ActorMethod<[], undefined>,
  'createTournament' : ActorMethod<[string], bigint>,
  'earnMythex' : ActorMethod<[bigint], undefined>,
  'earnResources' : ActorMethod<
    [bigint, bigint, bigint, bigint, bigint, bigint],
    undefined
  >,
  'forgeCards' : ActorMethod<[bigint, Array<bigint>], undefined>,
  'getAllBattleResults' : ActorMethod<[], Array<BattleResult>>,
  'getAllCraftingRecipes' : ActorMethod<[], Array<CraftingRecipe>>,
  'getAllMarketListings' : ActorMethod<[], Array<MarketTransaction>>,
  'getAllTournaments' : ActorMethod<[], Array<Tournament>>,
  'getBattleResult' : ActorMethod<[bigint], [] | [BattleResult]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCard' : ActorMethod<[bigint], [] | [Card]>,
  'getCraftingRecipe' : ActorMethod<[bigint], [] | [CraftingRecipe]>,
  'getDeck' : ActorMethod<[bigint], [] | [Deck]>,
  'getMarketListing' : ActorMethod<[bigint], [] | [MarketTransaction]>,
  'getMyCards' : ActorMethod<[], Array<Card>>,
  'getMyDecks' : ActorMethod<[], Array<Deck>>,
  'getMyMarketListings' : ActorMethod<[], Array<MarketTransaction>>,
  'getMyPlayerAccount' : ActorMethod<[], [] | [PlayerAccount]>,
  'getMySoftWallet' : ActorMethod<[], [] | [SoftWallet]>,
  'getMyStronghold' : ActorMethod<[], [] | [Stronghold]>,
  'getMythexBalance' : ActorMethod<[], bigint>,
  'getPlayerAccount' : ActorMethod<[bigint], [] | [PlayerAccount]>,
  'getPlayerCards' : ActorMethod<[Principal], Array<Card>>,
  'getPlayerDecks' : ActorMethod<[Principal], Array<Deck>>,
  'getSoftWallet' : ActorMethod<[Principal], [] | [SoftWallet]>,
  'getStronghold' : ActorMethod<[Principal], [] | [Stronghold]>,
  'getTournament' : ActorMethod<[bigint], [] | [Tournament]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'grantBattleRewards' : ActorMethod<[Principal, boolean], undefined>,
  'grantCardToPlayer' : ActorMethod<
    [Principal, string, bigint, string],
    bigint
  >,
  'grantTournamentRewards' : ActorMethod<[Principal, bigint], undefined>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinTournament' : ActorMethod<[bigint], undefined>,
  'recordBattle' : ActorMethod<[Principal, Principal, Principal], bigint>,
  'removeCard' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'spendMythex' : ActorMethod<[bigint], undefined>,
  'spendResources' : ActorMethod<
    [bigint, bigint, bigint, bigint, bigint, bigint],
    undefined
  >,
  'updateCard' : ActorMethod<
    [
      bigint,
      [] | [bigint],
      [] | [bigint],
      [] | [bigint],
      [] | [boolean],
      [] | [bigint],
      [] | [boolean],
    ],
    undefined
  >,
  'updateDeck' : ActorMethod<[bigint, string, Array<bigint>], undefined>,
  'updatePlayerAccount' : ActorMethod<[bigint, bigint], undefined>,
  'updateTournamentRankings' : ActorMethod<
    [bigint, Array<Principal>],
    undefined
  >,
  'upgradeStronghold' : ActorMethod<[bigint, Array<string>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];