import { CardData } from '../types/game';

// Canonical card library for Mythereum Retro — Original Mythereum style
// Each card has: attack, defense, magick generation, activated ability, HP modifier, edition
// Stats scaled to original game (ATK 20-80, DEF 15-60 range)
export const CARD_LIBRARY: CardData[] = [
  // ============================================================
  // WARRIORS (6 cards) — Strong ATK/DEF, White magick focus
  // ============================================================
  {
    id: 'warrior-001',
    name: 'Iron Vanguard',
    power: 45,
    cardType: 'Hero',
    description: 'A stalwart defender with unbreakable resolve',
    edition: 'Genesis',
    rarity: 'Common',
    class: 'Warrior',
    tags: ['Tank', 'Defense'],
    attack: 25,
    defense: 30,
    cost: 3,
    hpModifier: 10,
    magickGeneration: { white: 15, black: 0, grey: 5 },
    ability: {
      name: 'Fortify',
      description: 'Reduce incoming damage by 10 this turn',
      cost: { white: 1 },
      effect: { type: 'shield', amount: 10 },
    },
  },
  {
    id: 'warrior-002',
    name: 'Blade Master',
    power: 60,
    cardType: 'Hero',
    description: 'Swift strikes that cut through any defense',
    edition: 'Genesis',
    rarity: 'Rare',
    class: 'Warrior',
    tags: ['Attack', 'Speed'],
    attack: 40,
    defense: 25,
    cost: 4,
    hpModifier: -5,
    magickGeneration: { white: 10, black: 5, grey: 10 },
    ability: {
      name: 'Piercing Strike',
      description: 'Ignore 15 points of enemy defense this attack',
      cost: { white: 1, grey: 1 },
      effect: { type: 'piercing', amount: 15 },
    },
  },
  {
    id: 'warrior-003',
    name: 'Berserker King',
    power: 85,
    cardType: 'Hero',
    description: 'Unleashes devastating fury in battle',
    edition: 'Awakening',
    rarity: 'Epic',
    class: 'Warrior',
    tags: ['Attack', 'Fury'],
    attack: 55,
    defense: 25,
    cost: 6,
    hpModifier: -20,
    magickGeneration: { white: 5, black: 10, grey: 10 },
    ability: {
      name: 'Berserk Rage',
      description: '+30 ATK this turn but take 10 damage',
      cost: { black: 1, grey: 1 },
      effect: { type: 'attack_boost', amount: 30 },
    },
  },
  {
    id: 'warrior-004',
    name: 'Shield Guardian',
    power: 50,
    cardType: 'Hero',
    description: 'Protects allies with impenetrable defense',
    edition: 'Genesis',
    rarity: 'Rare',
    class: 'Warrior',
    tags: ['Tank', 'Support'],
    attack: 20,
    defense: 40,
    cost: 4,
    hpModifier: 20,
    magickGeneration: { white: 20, black: 0, grey: 5 },
    ability: {
      name: 'Shield Wall',
      description: 'Reduce incoming damage by 20 this turn',
      cost: { white: 2 },
      effect: { type: 'shield', amount: 20 },
    },
  },
  {
    id: 'warrior-005',
    name: 'Battle Champion',
    power: 75,
    cardType: 'Hero',
    description: 'Veteran of countless wars',
    edition: 'Awakening',
    rarity: 'Epic',
    class: 'Warrior',
    tags: ['Attack', 'Defense'],
    attack: 45,
    defense: 35,
    cost: 6,
    hpModifier: -10,
    magickGeneration: { white: 10, black: 5, grey: 10 },
    ability: {
      name: 'Superior Wit',
      description: '+20 ATK and +10 HP this turn',
      cost: { white: 1, grey: 2 },
      effect: { type: 'superior_wit', attack: 20, hp: 10 },
    },
  },
  {
    id: 'warrior-006',
    name: 'Warlord Supreme',
    power: 95,
    cardType: 'Hero',
    description: 'Commands the battlefield with absolute authority',
    edition: 'Survivor',
    rarity: 'Legendary',
    class: 'Warrior',
    tags: ['Attack', 'Leadership'],
    attack: 60,
    defense: 40,
    cost: 8,
    hpModifier: -30,
    magickGeneration: { white: 10, black: 10, grey: 15 },
    ability: {
      name: 'Rally Cry',
      description: '+10 ATK to all hand cards permanently',
      cost: { white: 2, grey: 2 },
      effect: { type: 'rally', amount: 10 },
    },
  },

  // ============================================================
  // MAGES (6 cards) — High ATK, low DEF, Black magick focus
  // ============================================================
  {
    id: 'mage-001',
    name: 'Frost Apprentice',
    power: 40,
    cardType: 'Hero',
    description: 'Wields the power of ice and cold',
    edition: 'Genesis',
    rarity: 'Common',
    class: 'Mage',
    tags: ['Magic', 'Control'],
    attack: 30,
    defense: 15,
    cost: 2,
    hpModifier: 5,
    magickGeneration: { white: 0, black: 15, grey: 10 },
    ability: {
      name: 'Frost Bolt',
      description: 'Stun enemy leader — they cannot attack next turn',
      cost: { black: 1, grey: 1 },
      effect: { type: 'stun' },
    },
  },
  {
    id: 'mage-002',
    name: 'Pyromancer',
    power: 65,
    cardType: 'Hero',
    description: 'Master of flame and destruction',
    edition: 'Genesis',
    rarity: 'Rare',
    class: 'Mage',
    tags: ['Magic', 'Damage'],
    attack: 50,
    defense: 15,
    cost: 5,
    hpModifier: -15,
    magickGeneration: { white: 0, black: 20, grey: 10 },
    ability: {
      name: 'Incinerate',
      description: '+25 ATK this turn, piercing through defense',
      cost: { black: 2, grey: 1 },
      effect: { type: 'attack_boost', amount: 25 },
    },
  },
  {
    id: 'mage-003',
    name: 'Archmage Supreme',
    power: 90,
    cardType: 'Hero',
    description: 'Commands all elements with supreme mastery',
    edition: 'Survivor',
    rarity: 'Legendary',
    class: 'Mage',
    tags: ['Magic', 'Power'],
    attack: 65,
    defense: 25,
    cost: 8,
    hpModifier: -35,
    magickGeneration: { white: 5, black: 20, grey: 20 },
    ability: {
      name: 'Annihilate',
      description: 'Infinite attack — destroy any leader instantly',
      cost: { black: 3, grey: 2 },
      effect: { type: 'annihilate' },
    },
  },
  {
    id: 'mage-004',
    name: 'Storm Caller',
    power: 70,
    cardType: 'Hero',
    description: 'Summons lightning from the heavens',
    edition: 'Awakening',
    rarity: 'Epic',
    class: 'Mage',
    tags: ['Magic', 'Lightning'],
    attack: 55,
    defense: 18,
    cost: 6,
    hpModifier: -20,
    magickGeneration: { white: 5, black: 15, grey: 15 },
    ability: {
      name: 'Chain Lightning',
      description: 'Deal 15 direct damage to player HP',
      cost: { black: 2, grey: 1 },
      effect: { type: 'drain', amount: 15 },
    },
  },
  {
    id: 'mage-005',
    name: 'Void Sorcerer',
    power: 55,
    cardType: 'Hero',
    description: 'Manipulates dark energies',
    edition: 'Genesis',
    rarity: 'Rare',
    class: 'Mage',
    tags: ['Magic', 'Dark'],
    attack: 40,
    defense: 18,
    cost: 5,
    hpModifier: -10,
    magickGeneration: { white: 0, black: 25, grey: 5 },
    ability: {
      name: 'Void Drain',
      description: 'Steal 2 Black magick from opponent',
      cost: { black: 1 },
      effect: { type: 'magick_drain', color: 'black', amount: 2 },
    },
  },
  {
    id: 'mage-006',
    name: 'Chronomancer',
    power: 80,
    cardType: 'Hero',
    description: 'Bends time to their will',
    edition: 'Awakening',
    rarity: 'Epic',
    class: 'Mage',
    tags: ['Magic', 'Time'],
    attack: 50,
    defense: 22,
    cost: 7,
    hpModifier: -25,
    magickGeneration: { white: 10, black: 15, grey: 15 },
    ability: {
      name: 'Time Warp',
      description: '+40 ATK this turn',
      cost: { black: 2, grey: 2 },
      effect: { type: 'attack_boost', amount: 40 },
    },
  },

  // ============================================================
  // ROGUES (5 cards) — Tricky, Grey magick focus
  // ============================================================
  {
    id: 'rogue-001',
    name: 'Shadow Scout',
    power: 35,
    cardType: 'Hero',
    description: 'Moves unseen through the darkness',
    edition: 'Genesis',
    rarity: 'Common',
    class: 'Rogue',
    tags: ['Stealth', 'Speed'],
    attack: 30,
    defense: 15,
    cost: 2,
    hpModifier: 5,
    magickGeneration: { white: 0, black: 5, grey: 20 },
    ability: {
      name: 'Hide',
      description: 'Become untargetable — infinite defense this turn',
      cost: { black: 1, grey: 1 },
      effect: { type: 'hide' },
    },
  },
  {
    id: 'rogue-002',
    name: 'Master Assassin',
    power: 70,
    cardType: 'Hero',
    description: 'Strikes from the shadows with lethal precision',
    edition: 'Awakening',
    rarity: 'Epic',
    class: 'Rogue',
    tags: ['Stealth', 'Critical'],
    attack: 55,
    defense: 18,
    cost: 5,
    hpModifier: -15,
    magickGeneration: { white: 0, black: 10, grey: 20 },
    ability: {
      name: 'Assassinate',
      description: '+35 ATK and ignore half of enemy defense',
      cost: { black: 1, grey: 3 },
      effect: { type: 'attack_boost', amount: 35 },
    },
  },
  {
    id: 'rogue-003',
    name: 'Night Blade',
    power: 58,
    cardType: 'Hero',
    description: 'Silent death in the darkness',
    edition: 'Genesis',
    rarity: 'Rare',
    class: 'Rogue',
    tags: ['Stealth', 'Poison'],
    attack: 42,
    defense: 18,
    cost: 4,
    hpModifier: -5,
    magickGeneration: { white: 0, black: 10, grey: 15 },
    ability: {
      name: 'Poison Blade',
      description: 'Deal 10 direct damage to enemy player HP',
      cost: { grey: 2 },
      effect: { type: 'drain', amount: 10 },
    },
  },
  {
    id: 'rogue-004',
    name: 'Phantom Thief',
    power: 48,
    cardType: 'Hero',
    description: 'Steals victory from under your nose',
    edition: 'Genesis',
    rarity: 'Rare',
    class: 'Rogue',
    tags: ['Stealth', 'Evasion'],
    attack: 35,
    defense: 20,
    cost: 4,
    hpModifier: 0,
    magickGeneration: { white: 5, black: 5, grey: 15 },
    ability: {
      name: 'Steal Magick',
      description: 'Steal 2 Grey magick from opponent',
      cost: { grey: 1 },
      effect: { type: 'magick_drain', color: 'grey', amount: 2 },
    },
  },
  {
    id: 'rogue-005',
    name: 'Shadow Lord',
    power: 82,
    cardType: 'Hero',
    description: 'Master of all shadow arts',
    edition: 'Survivor',
    rarity: 'Legendary',
    class: 'Rogue',
    tags: ['Stealth', 'Master'],
    attack: 60,
    defense: 22,
    cost: 7,
    hpModifier: -25,
    magickGeneration: { white: 5, black: 15, grey: 25 },
    ability: {
      name: 'Shadow Strike',
      description: 'Deal damage + lifesteal 50% as player HP',
      cost: { black: 2, grey: 3 },
      effect: { type: 'lifesteal', percent: 50 },
    },
  },

  // ============================================================
  // HEALERS (4 cards) — High DEF, White magick focus, support
  // ============================================================
  {
    id: 'cleric-001',
    name: 'Holy Acolyte',
    power: 30,
    cardType: 'Hero',
    description: 'Channels divine light to heal and protect',
    edition: 'Genesis',
    rarity: 'Common',
    class: 'Healer',
    tags: ['Healing', 'Support'],
    attack: 15,
    defense: 30,
    cost: 2,
    hpModifier: 15,
    magickGeneration: { white: 25, black: 0, grey: 5 },
    ability: {
      name: 'Divine Heal',
      description: 'Heal leader for 15 HP',
      cost: { white: 1 },
      effect: { type: 'hp_boost', amount: 15 },
    },
  },
  {
    id: 'cleric-002',
    name: 'Divine Paladin',
    power: 55,
    cardType: 'Hero',
    description: 'A beacon of hope and righteousness',
    edition: 'Awakening',
    rarity: 'Rare',
    class: 'Healer',
    tags: ['Healing', 'Defense'],
    attack: 30,
    defense: 35,
    cost: 5,
    hpModifier: 10,
    magickGeneration: { white: 20, black: 0, grey: 10 },
    ability: {
      name: 'Consecrate',
      description: '+15 DEF and heal 10 HP',
      cost: { white: 2 },
      effect: { type: 'superior_wit', attack: 0, hp: 10 },
    },
  },
  {
    id: 'cleric-003',
    name: 'High Priest',
    power: 68,
    cardType: 'Hero',
    description: 'Blessed by the gods themselves',
    edition: 'Awakening',
    rarity: 'Epic',
    class: 'Healer',
    tags: ['Healing', 'Holy'],
    attack: 25,
    defense: 40,
    cost: 6,
    hpModifier: 20,
    magickGeneration: { white: 30, black: 0, grey: 10 },
    ability: {
      name: 'Resurrection',
      description: 'Heal leader for 25 HP',
      cost: { white: 3 },
      effect: { type: 'hp_boost', amount: 25 },
    },
  },
  {
    id: 'cleric-004',
    name: 'Celestial Guardian',
    power: 78,
    cardType: 'Hero',
    description: 'Divine protector of the faithful',
    edition: 'Survivor',
    rarity: 'Epic',
    class: 'Healer',
    tags: ['Healing', 'Protection'],
    attack: 30,
    defense: 45,
    cost: 7,
    hpModifier: 15,
    magickGeneration: { white: 25, black: 0, grey: 15 },
    ability: {
      name: 'Aegis of Light',
      description: 'Shield for 25 damage and heal 10 HP',
      cost: { white: 3, grey: 1 },
      effect: { type: 'shield', amount: 25 },
    },
  },

  // ============================================================
  // RANGERS (5 cards) — Balanced, Grey + White magick
  // ============================================================
  {
    id: 'ranger-001',
    name: 'Forest Tracker',
    power: 38,
    cardType: 'Hero',
    description: 'Expert marksman with keen senses',
    edition: 'Genesis',
    rarity: 'Common',
    class: 'Ranger',
    tags: ['Ranged', 'Precision'],
    attack: 30,
    defense: 20,
    cost: 3,
    hpModifier: 5,
    magickGeneration: { white: 10, black: 0, grey: 15 },
    ability: {
      name: 'Precision Shot',
      description: '+15 ATK and ignore some defense',
      cost: { grey: 1 },
      effect: { type: 'attack_boost', amount: 15 },
    },
  },
  {
    id: 'ranger-002',
    name: 'Beast Master',
    power: 62,
    cardType: 'Hero',
    description: 'Commands wild creatures in battle',
    edition: 'Awakening',
    rarity: 'Rare',
    class: 'Ranger',
    tags: ['Ranged', 'Summon'],
    attack: 38,
    defense: 28,
    cost: 5,
    hpModifier: 0,
    magickGeneration: { white: 10, black: 5, grey: 15 },
    ability: {
      name: 'Beast Charge',
      description: '+20 ATK this turn',
      cost: { grey: 2 },
      effect: { type: 'attack_boost', amount: 20 },
    },
  },
  {
    id: 'ranger-003',
    name: 'Eagle Eye',
    power: 52,
    cardType: 'Hero',
    description: 'Never misses their mark',
    edition: 'Genesis',
    rarity: 'Rare',
    class: 'Ranger',
    tags: ['Ranged', 'Accuracy'],
    attack: 42,
    defense: 18,
    cost: 4,
    hpModifier: -5,
    magickGeneration: { white: 5, black: 5, grey: 20 },
    ability: {
      name: 'Aimed Shot',
      description: 'Ignore 20 points of enemy defense',
      cost: { grey: 2 },
      effect: { type: 'piercing', amount: 20 },
    },
  },
  {
    id: 'ranger-004',
    name: 'Wilderness Warden',
    power: 72,
    cardType: 'Hero',
    description: 'Guardian of the ancient forests',
    edition: 'Awakening',
    rarity: 'Epic',
    class: 'Ranger',
    tags: ['Ranged', 'Nature'],
    attack: 40,
    defense: 32,
    cost: 6,
    hpModifier: 5,
    magickGeneration: { white: 15, black: 0, grey: 15 },
    ability: {
      name: 'Nature\'s Blessing',
      description: 'Heal leader 15 HP and +10 ATK',
      cost: { white: 1, grey: 2 },
      effect: { type: 'superior_wit', attack: 10, hp: 15 },
    },
  },
  {
    id: 'ranger-005',
    name: 'Apex Hunter',
    power: 88,
    cardType: 'Hero',
    description: 'The ultimate predator',
    edition: 'Survivor',
    rarity: 'Legendary',
    class: 'Ranger',
    tags: ['Ranged', 'Elite'],
    attack: 58,
    defense: 28,
    cost: 8,
    hpModifier: -20,
    magickGeneration: { white: 10, black: 10, grey: 20 },
    ability: {
      name: 'Kill Shot',
      description: '+45 ATK — a devastating finishing blow',
      cost: { grey: 3, black: 1 },
      effect: { type: 'attack_boost', amount: 45 },
    },
  },
];
