import { CardData } from '../types/game';

// Canonical card library for Mythereum Retro with complete battle stats
// Expanded to 24+ unique hero cards across all 5 classes
export const CARD_LIBRARY: CardData[] = [
  // Warriors (6 cards)
  {
    id: 'warrior-001',
    name: 'Iron Vanguard',
    power: 45,
    cardType: 'Hero',
    description: 'A stalwart defender with unbreakable resolve',
    edition: 'Genesis',
    rarity: 'Common',
    class: 'Warrior',
    tags: ['Tank', 'Defense'],
    attack: 3,
    defense: 5,
    cost: 3,
    manaRequirement: { mana: 2 },
  },
  {
    id: 'warrior-002',
    name: 'Blade Master',
    power: 60,
    cardType: 'Hero',
    description: 'Swift strikes that cut through any defense',
    edition: 'Genesis',
    rarity: 'Rare',
    class: 'Warrior',
    tags: ['Attack', 'Speed'],
    attack: 5,
    defense: 3,
    cost: 4,
    manaRequirement: { mana: 3 },
  },
  {
    id: 'warrior-003',
    name: 'Berserker King',
    power: 85,
    cardType: 'Hero',
    description: 'Unleashes devastating fury in battle',
    edition: 'Genesis',
    rarity: 'Epic',
    class: 'Warrior',
    tags: ['Attack', 'Fury'],
    attack: 7,
    defense: 4,
    cost: 6,
    manaRequirement: { mana: 5 },
  },
  {
    id: 'warrior-004',
    name: 'Shield Guardian',
    power: 50,
    cardType: 'Hero',
    description: 'Protects allies with impenetrable defense',
    edition: 'Genesis',
    rarity: 'Rare',
    class: 'Warrior',
    tags: ['Tank', 'Support'],
    attack: 2,
    defense: 6,
    cost: 4,
    manaRequirement: { mana: 3 },
  },
  {
    id: 'warrior-005',
    name: 'Battle Champion',
    power: 75,
    cardType: 'Hero',
    description: 'Veteran of countless wars',
    edition: 'Genesis',
    rarity: 'Epic',
    class: 'Warrior',
    tags: ['Attack', 'Defense'],
    attack: 6,
    defense: 5,
    cost: 6,
    manaRequirement: { mana: 5 },
  },
  {
    id: 'warrior-006',
    name: 'Warlord Supreme',
    power: 95,
    cardType: 'Hero',
    description: 'Commands the battlefield with absolute authority',
    edition: 'Genesis',
    rarity: 'Legendary',
    class: 'Warrior',
    tags: ['Attack', 'Leadership'],
    attack: 8,
    defense: 6,
    cost: 8,
    manaRequirement: { mana: 7 },
  },
  
  // Mages (6 cards)
  {
    id: 'mage-001',
    name: 'Frost Apprentice',
    power: 40,
    cardType: 'Hero',
    description: 'Wields the power of ice and cold',
    edition: 'Genesis',
    rarity: 'Common',
    class: 'Mage',
    tags: ['Magic', 'Control'],
    attack: 2,
    defense: 3,
    cost: 2,
    manaRequirement: { mana: 2, magick: 1 },
  },
  {
    id: 'mage-002',
    name: 'Pyromancer',
    power: 65,
    cardType: 'Hero',
    description: 'Master of flame and destruction',
    edition: 'Genesis',
    rarity: 'Rare',
    class: 'Mage',
    tags: ['Magic', 'Damage'],
    attack: 6,
    defense: 2,
    cost: 5,
    manaRequirement: { mana: 4, magick: 2 },
  },
  {
    id: 'mage-003',
    name: 'Archmage Supreme',
    power: 90,
    cardType: 'Hero',
    description: 'Commands all elements with supreme mastery',
    edition: 'Genesis',
    rarity: 'Legendary',
    class: 'Mage',
    tags: ['Magic', 'Power'],
    attack: 8,
    defense: 5,
    cost: 8,
    manaRequirement: { mana: 6, magick: 3 },
  },
  {
    id: 'mage-004',
    name: 'Storm Caller',
    power: 70,
    cardType: 'Hero',
    description: 'Summons lightning from the heavens',
    edition: 'Genesis',
    rarity: 'Epic',
    class: 'Mage',
    tags: ['Magic', 'Lightning'],
    attack: 7,
    defense: 3,
    cost: 6,
    manaRequirement: { mana: 5, magick: 2 },
  },
  {
    id: 'mage-005',
    name: 'Void Sorcerer',
    power: 55,
    cardType: 'Hero',
    description: 'Manipulates dark energies',
    edition: 'Genesis',
    rarity: 'Rare',
    class: 'Mage',
    tags: ['Magic', 'Dark'],
    attack: 5,
    defense: 3,
    cost: 5,
    manaRequirement: { mana: 4, magick: 2 },
  },
  {
    id: 'mage-006',
    name: 'Chronomancer',
    power: 80,
    cardType: 'Hero',
    description: 'Bends time to their will',
    edition: 'Genesis',
    rarity: 'Epic',
    class: 'Mage',
    tags: ['Magic', 'Time'],
    attack: 6,
    defense: 4,
    cost: 7,
    manaRequirement: { mana: 6, magick: 3 },
  },
  
  // Rogues (5 cards)
  {
    id: 'rogue-001',
    name: 'Shadow Scout',
    power: 35,
    cardType: 'Hero',
    description: 'Moves unseen through the darkness',
    edition: 'Genesis',
    rarity: 'Common',
    class: 'Rogue',
    tags: ['Stealth', 'Speed'],
    attack: 4,
    defense: 2,
    cost: 2,
    manaRequirement: { mana: 1 },
  },
  {
    id: 'rogue-002',
    name: 'Master Assassin',
    power: 70,
    cardType: 'Hero',
    description: 'Strikes from the shadows with lethal precision',
    edition: 'Genesis',
    rarity: 'Epic',
    class: 'Rogue',
    tags: ['Stealth', 'Critical'],
    attack: 7,
    defense: 3,
    cost: 5,
    manaRequirement: { mana: 4 },
  },
  {
    id: 'rogue-003',
    name: 'Night Blade',
    power: 58,
    cardType: 'Hero',
    description: 'Silent death in the darkness',
    edition: 'Genesis',
    rarity: 'Rare',
    class: 'Rogue',
    tags: ['Stealth', 'Poison'],
    attack: 6,
    defense: 2,
    cost: 4,
    manaRequirement: { mana: 3 },
  },
  {
    id: 'rogue-004',
    name: 'Phantom Thief',
    power: 48,
    cardType: 'Hero',
    description: 'Steals victory from under your nose',
    edition: 'Genesis',
    rarity: 'Rare',
    class: 'Rogue',
    tags: ['Stealth', 'Evasion'],
    attack: 5,
    defense: 3,
    cost: 4,
    manaRequirement: { mana: 3 },
  },
  {
    id: 'rogue-005',
    name: 'Shadow Lord',
    power: 82,
    cardType: 'Hero',
    description: 'Master of all shadow arts',
    edition: 'Genesis',
    rarity: 'Legendary',
    class: 'Rogue',
    tags: ['Stealth', 'Master'],
    attack: 8,
    defense: 4,
    cost: 7,
    manaRequirement: { mana: 6 },
  },
  
  // Clerics/Healers (4 cards)
  {
    id: 'cleric-001',
    name: 'Holy Acolyte',
    power: 30,
    cardType: 'Hero',
    description: 'Channels divine light to heal and protect',
    edition: 'Genesis',
    rarity: 'Common',
    class: 'Healer',
    tags: ['Healing', 'Support'],
    attack: 1,
    defense: 4,
    cost: 2,
    manaRequirement: { mana: 2 },
  },
  {
    id: 'cleric-002',
    name: 'Divine Paladin',
    power: 55,
    cardType: 'Hero',
    description: 'A beacon of hope and righteousness',
    edition: 'Genesis',
    rarity: 'Rare',
    class: 'Healer',
    tags: ['Healing', 'Defense'],
    attack: 4,
    defense: 5,
    cost: 5,
    manaRequirement: { mana: 4 },
  },
  {
    id: 'cleric-003',
    name: 'High Priest',
    power: 68,
    cardType: 'Hero',
    description: 'Blessed by the gods themselves',
    edition: 'Genesis',
    rarity: 'Epic',
    class: 'Healer',
    tags: ['Healing', 'Holy'],
    attack: 3,
    defense: 6,
    cost: 6,
    manaRequirement: { mana: 5, magick: 1 },
  },
  {
    id: 'cleric-004',
    name: 'Celestial Guardian',
    power: 78,
    cardType: 'Hero',
    description: 'Divine protector of the faithful',
    edition: 'Genesis',
    rarity: 'Epic',
    class: 'Healer',
    tags: ['Healing', 'Protection'],
    attack: 5,
    defense: 6,
    cost: 7,
    manaRequirement: { mana: 6, magick: 2 },
  },
  
  // Rangers (5 cards)
  {
    id: 'ranger-001',
    name: 'Forest Tracker',
    power: 38,
    cardType: 'Hero',
    description: 'Expert marksman with keen senses',
    edition: 'Genesis',
    rarity: 'Common',
    class: 'Ranger',
    tags: ['Ranged', 'Precision'],
    attack: 4,
    defense: 3,
    cost: 3,
    manaRequirement: { mana: 2 },
  },
  {
    id: 'ranger-002',
    name: 'Beast Master',
    power: 62,
    cardType: 'Hero',
    description: 'Commands wild creatures in battle',
    edition: 'Genesis',
    rarity: 'Rare',
    class: 'Ranger',
    tags: ['Ranged', 'Summon'],
    attack: 5,
    defense: 4,
    cost: 5,
    manaRequirement: { mana: 4 },
  },
  {
    id: 'ranger-003',
    name: 'Eagle Eye',
    power: 52,
    cardType: 'Hero',
    description: 'Never misses their mark',
    edition: 'Genesis',
    rarity: 'Rare',
    class: 'Ranger',
    tags: ['Ranged', 'Accuracy'],
    attack: 6,
    defense: 2,
    cost: 4,
    manaRequirement: { mana: 3 },
  },
  {
    id: 'ranger-004',
    name: 'Wilderness Warden',
    power: 72,
    cardType: 'Hero',
    description: 'Guardian of the ancient forests',
    edition: 'Genesis',
    rarity: 'Epic',
    class: 'Ranger',
    tags: ['Ranged', 'Nature'],
    attack: 6,
    defense: 5,
    cost: 6,
    manaRequirement: { mana: 5 },
  },
  {
    id: 'ranger-005',
    name: 'Apex Hunter',
    power: 88,
    cardType: 'Hero',
    description: 'The ultimate predator',
    edition: 'Genesis',
    rarity: 'Legendary',
    class: 'Ranger',
    tags: ['Ranged', 'Elite'],
    attack: 9,
    defense: 4,
    cost: 8,
    manaRequirement: { mana: 7 },
  },
];
